language: java
sudo: true
services:
  - docker
jdk: openjdk8
env:
  global:
    - SHA=$(git rev-parse HEAD)

before_install:
  - chmod +x mvnw

script:
  - mvn clean install

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./docker_push.sh
