language: java
sudo: required
services:
  - docker
jdk:
  - oralcejdk8
env:
  global:
    -SHA=$(git rev-parse HEAD)

script:
  - mvn clean install

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - docker build -t ibrahimsobhy/hadeeth-pro-people-info:latest -t ibrahimsobhy/hadeeth-pro-people-info:$SHA .
  - docker push ibrahimsobhy/hadeeth-pro-people-info:latest
  - docker push ibrahimsobhy/hadeeth-pro-people-info:$SHA
